### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by maccelerated** [leecade/koa-webpack-middleware#2]
Occurs when the page is requested before the webpack finishes compiling.

**Comment by leecade** [comment]
yeah I notice that too, will do more test and fix it soon

**Comment by balzaczyy** [comment]
It appears that the middle should hold the request since it mention 'wait until bundle finished'. However the request just returns 404. Maybe it caused the above error? And it's blocking me from further try.

**Comment by lostpebble** [comment]
It appears Koa isn't waiting until webpack has finished building the bundle before sending a response, and then the middleware eventually finishes building and tries to send a response afterwards- which by then is too late and causes a server error.

The server has to be restarted and we manually have to wait until we see the bundle finished building. After many hours of development and working on the server code, it gets a bit frustrating. I tried forking this and working it out, but my experience with the internals of NodeJS and Koa request / response is limited and I couldn't fix it unfortunately.

Has there been any progress on this issue?

**Comment by leecade** [comment]
closed #14

**Comment by sanketmeghani** [comment]
I am seeing this issue with koa-webpack-middleware@1.0.5 but the issue is not observed with koa-webpack-middleware@1.0.3. I am using it with koa@2.0.0 & webpack@2.6.1. Any clue what I might be missing?

With 1.5.0, I am getting following error:
`
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at Object.set (**************************************\node_modules\koa\lib\response.js:440:16)
    at Object.proto.(anonymous function) [as set] (**************************************\node_modules\delegates\index.js:40:31)
    at Object.setHeader (**************************************\node_modules\koa-webpack-middleware\lib\devMiddleware.js:29:23)
    at Object.handleRangeHeaders (**************************************\node_modules\webpack-dev-middleware\lib\Shared.js:61:8)
    at processRequest (**************************************\node_modules\webpack-dev-middleware\middleware.js:63:21)
    at continueBecauseBundleAvailable (**************************************\node_modules\webpack-dev-middleware\lib\Shared.js:122:6)
    at Array.forEach (native)
    at **************************************\node_modules\webpack-dev-middleware\lib\Shared.js:121:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
`
